version: 2.1

# orbs:
#   ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
      - run:
          name: Bundler Version
          command: bundle --version
      - run:
          name: Install Dependencies
          command: bundle install
      - run:
          name: Continuous Integration Tasks
          command: rake

workflows:
  version: 2

  build_and_test:
    jobs:
      - build

