version: 2.1

# orbs:
#   ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          command: bundle install
      - run:
          command: rubocop

workflows:
  version: 2

  build_and_test:
    jobs:
      - build

