name: build_and_test
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: |
          gem install bundler
          bundle --version
          bundle install --jobs 3
          bundle exec rake ci:env
          bundle exec rake
