name: build-and-test
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Setup Dependencies
        run: |
          gem install bundler
          bundle --version
          bundle install --jobs 3
          bundle exec rake ci:env
      - name: Build
        run: bundle exec rake project:build
      - name: Lint and Test
        run: bundle exec rake
